"""Add Sede and SedeCareer

Revision ID: d43b6464a465
Revises: 
Create Date: 2026-07-29 15:02:16.586202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd43b6464a465'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('careers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('faculty', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_careers_faculty'), 'careers', ['faculty'], unique=False)
    op.create_index(op.f('ix_careers_id'), 'careers', ['id'], unique=False)
    op.create_index(op.f('ix_careers_name'), 'careers', ['name'], unique=False)
    op.create_table('gestiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gestiones_id'), 'gestiones', ['id'], unique=False)
    op.create_index(op.f('ix_gestiones_name'), 'gestiones', ['name'], unique=False)
    op.create_table('sedes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sedes_id'), 'sedes', ['id'], unique=False)
    op.create_index(op.f('ix_sedes_name'), 'sedes', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('admin', 'research', 'coordinator', 'teacher', name='roleenum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('academic_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('career_id', sa.Integer(), nullable=True),
    sa.Column('gestion_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('origin_color', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['career_id'], ['careers.id'], ),
    sa.ForeignKeyConstraint(['gestion_id'], ['gestiones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_academic_activities_id'), 'academic_activities', ['id'], unique=False)
    op.create_index(op.f('ix_academic_activities_title'), 'academic_activities', ['title'], unique=False)
    op.create_table('scientific_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('career_id', sa.Integer(), nullable=True),
    sa.Column('gestion_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('activity_type', sa.Enum('congreso', 'webinar', 'defensa', 'feria', 'olimpiada', 'master_class', name='scientificactivitytype'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('responsible_name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'in_progress', 'completed', 'cancelled', name='scientificactivitystatus'), nullable=False),
    sa.Column('evidence_url', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['career_id'], ['careers.id'], ),
    sa.ForeignKeyConstraint(['gestion_id'], ['gestiones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scientific_activities_id'), 'scientific_activities', ['id'], unique=False)
    op.create_index(op.f('ix_scientific_activities_title'), 'scientific_activities', ['title'], unique=False)
    op.create_table('sede_career',
    sa.Column('sede_id', sa.Integer(), nullable=False),
    sa.Column('career_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['career_id'], ['careers.id'], ),
    sa.ForeignKeyConstraint(['sede_id'], ['sedes.id'], ),
    sa.PrimaryKeyConstraint('sede_id', 'career_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sede_career')
    op.drop_index(op.f('ix_scientific_activities_title'), table_name='scientific_activities')
    op.drop_index(op.f('ix_scientific_activities_id'), table_name='scientific_activities')
    op.drop_table('scientific_activities')
    op.drop_index(op.f('ix_academic_activities_title'), table_name='academic_activities')
    op.drop_index(op.f('ix_academic_activities_id'), table_name='academic_activities')
    op.drop_table('academic_activities')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sedes_name'), table_name='sedes')
    op.drop_index(op.f('ix_sedes_id'), table_name='sedes')
    op.drop_table('sedes')
    op.drop_index(op.f('ix_gestiones_name'), table_name='gestiones')
    op.drop_index(op.f('ix_gestiones_id'), table_name='gestiones')
    op.drop_table('gestiones')
    op.drop_index(op.f('ix_careers_name'), table_name='careers')
    op.drop_index(op.f('ix_careers_id'), table_name='careers')
    op.drop_index(op.f('ix_careers_faculty'), table_name='careers')
    op.drop_table('careers')
    # ### end Alembic commands ###
